# Generated by Django 2.0.7 on 2018-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petal_height', models.FloatField(default=0)),
                ('petal_width', models.FloatField(default=0)),
                ('sepal_height', models.FloatField(default=0)),
                ('sepal_width', models.FloatField(default=0)),
            ],
        ),
    ]
