# Generated by Django 2.0.7 on 2018-07-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_iris_iris_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iris',
            options={'verbose_name_plural': 'irises'},
        ),
    ]
